### ISSUE TITLE
Paper/code discrepancies and PR for case studies in Python

### ISSUE THREAD

**Issue by taodav** [eaplatanios/jelly-bean-world#10]
Hey! First off I'd like to say this is a great idea for a framework - it's just small enough for people to thoroughly test ideas on continual and non-stationary RL problems. Thanks for putting it out here!

I'm currently re-implementing the case studies mentioned in the paper in Python and came into a few discrepancies I wanted to ask about:

1. In the paper for bananas and jellybeans, you have a PiecewiseBox interaction with walls, whereas in the `Configurations.swift` file you have this same interaction with trees (itemId 4) instead of walls (itemId 3). Which interaction was used in the experiments in the paper?
2. There's also a discrepancy between the onion intensities in the paper and in `Configurations.swift` - in the paper the onion intensity is +1.5, whereas in the code it's -3.0. I'm assuming it's meant to be -3.0? At +1.5 the board is FILLED with onions

I was also wondering if you would be interested in me submitting a PR for the Python implementation of your case studies? It seems that some people might be interested!

**Comment by asaparov** [comment]
Yes definitely, we would really appreciate help with implementing that functionality in Python.

And yes I think you're right about both of those discrepancies. The values in `Configurations.swift` are the ones we used in the experiments.

**Comment by taodav** [comment]
Ahh I see, thanks for clarifying!

Great, I'll submit a PR!
