### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by NishanthVAnand** [eaplatanios/jelly-bean-world#15]
Hi,

I am using MacOS (v12.2.1) and I get the following error when installing the jbw package:
```
../../jbw/deps/core/io.h:80:10: fatal error: 'uchar.h' file not found
#include <uchar.h>
```
Any idea how to fix this?

**Comment by asaparov** [comment]
Ah apparently macOS versions < 13 don't provide `uchar.h` despite being part of the C/C++ standard. I don't have access to a Mac to test this, but I tried to push some changes to workaround this issue. Please let me know if it works or if there are any compiler warnings/errors.

**Comment by NishanthVAnand** [comment]
```
In file included from ../../jbw/deps/core/random.h:21:
../../jbw/deps/core/io.h:85:18: error: cannot combine with previous 'type-name' declaration specifier
typedef uint32_t char32_t;
                 ^
../../jbw/deps/core/io.h:85:1: warning: typedef requires a name [-Wmissing-declarations]
typedef uint32_t char32_t;
^~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
error: command '/usr/bin/clang' failed with exit code 1

```

There's a new error now.

**Comment by asaparov** [comment]
Thanks for testing it. I pushed another change. Please let me know if that fixes it or not.
