### ISSUE TITLE
pip support

### ISSUE THREAD

**Issue by finbarrtimbers** [eaplatanios/jelly-bean-world#20]
Have you looked into making this available via pip? If not, I'm happy to look into contributing a PR.

**Comment by asaparov** [comment]
Oh that's a good idea. We haven't considered doing that, but a PR would be very welcome!

**Comment by asaparov** [comment]
We just merged a pull request from [Chris Chow](https://github.com/ckchow) adding support for this.

**Comment by finbarrtimbers** [comment]
Incredible! Thank you!
