### ISSUE TITLE
Error when using jbw

### ISSUE THREAD

**Issue by thunanguyen** [eaplatanios/jelly-bean-world#6]
I follow the instruction to install jbw like in the readme but when I import jbw in python, it keeps saying ImportError: cannot import name 'simulator_c'. What is the problem?

**Comment by thunanguyen** [comment]
I test it with Anaconda on Window with python 3.6 python 3.7, use msvc and mingw to build. All ends up build successfully without any errors but when import jbw, that 'simulator_c' error occurs

**Comment by asaparov** [comment]
Oh did you try this in the `api\python` directory? I'm not entirely sure why, but `import jbw` produces that error when I try it from that directory. Maybe something to do with the Python import system? Try importing it in a different directory.

**Comment by thunanguyen** [comment]
Oddly enough, it spills out another strange error

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Workspace\envs\mujoco\lib\site-packages\jbw\__init__.py", line 19, in <module>
    from . import environments
  File "C:\Workspace\envs\mujoco\lib\site-packages\jbw\environments.py", line 75, in <module>
    sim_config = make_config()
  File "C:\Workspace\envs\mujoco\lib\site-packages\jbw\environments.py", line 68, in make_config
    allowed_movement_directions=[jbw.ActionPolicy.ALLOWED, jbw.ActionPolicy.DISALLOWED, jbw.ActionPolicy.DISALLOWED, jbw.ActionPolicy.DISALLOWED],
NameError: name 'jbw' is not defined`

**Comment by eaplatanios** [comment]
Yes if you have a directory with the same name the python interpreter will try to import from there and so you need to be outside that directory in order for it to pick up the one from site-packages.

**Comment by thunanguyen** [comment]
Hm, I import it from outside of that folder and it gives the above 'jbw' is not defined error

**Comment by eaplatanios** [comment]
I think that’s a bug and we should remove the “jbw.” from that line.

**Comment by eaplatanios** [comment]
I’m not on my computer right now but you could try removing the “jbw.” from that line and reinstalling the package. I’ll also check once I get to my computer.

**Comment by thunanguyen** [comment]
Yes that is a bug, removing jbw does help but also in line 29 I think should be from .visualizer import MapVisualizer, pi or else it will give the 'pi' is not defined error
